# Generated by Django 4.2.6 on 2023-10-09 11:11

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lander_portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Exams',
            fields=[
                ('Exam_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_Type', models.CharField(max_length=100)),
                ('Exam_Image', models.FileField(default='/learn-2.svg', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', ' pnm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', ' tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])])),
                ('Exam_shortForm', models.CharField(default=' ', max_length=100)),
                ('Exam_Desc', ckeditor.fields.RichTextField(default='Add Course Description')),
                ('Exam_Add_Time', models.DateField(auto_now_add=True)),
                ('Exam_Update_Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags_toMatch',
            fields=[
                ('Tag_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tag_Type', models.CharField(max_length=100)),
                ('Tag_Add_Time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics_comes',
            fields=[
                ('Topic_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Topic_Type', models.CharField(max_length=100)),
                ('Topic_slug', models.SlugField(max_length=200)),
                ('Topic_Desc', ckeditor.fields.RichTextField(default='Add Topic Description')),
                ('Topic_Add_Time', models.DateField(auto_now_add=True)),
                ('Topic_Update_Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_toStudy',
            fields=[
                ('Subj_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Subj_Type', models.CharField(max_length=100)),
                ('Subj_Desc', ckeditor.fields.RichTextField(default='Add Subject Description')),
                ('Subj_Add_Time', models.DateField(auto_now_add=True)),
                ('Subj_Update_Time', models.DateField(auto_now=True)),
                ('Topic_Id', models.ManyToManyField(to='lander_portal.topics_comes')),
            ],
        ),
        migrations.CreateModel(
            name='Question_data',
            fields=[
                ('Question_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question_show', models.CharField(default='?', max_length=1000)),
                ('Question_detail', ckeditor.fields.RichTextField()),
                ('Question_Options', models.CharField(max_length=100)),
                ('Question_Correct_Option', models.CharField(max_length=50)),
                ('Question_Ans_Explain', ckeditor.fields.RichTextField()),
                ('Question_Add_Time', models.DateField(auto_now_add=True)),
                ('Question_Update_Time', models.DateField(auto_now=True)),
                ('Creater_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Exam_Id', models.ManyToManyField(to='lander_portal.courses_exams')),
                ('Topic_Id', models.ManyToManyField(to='lander_portal.topics_comes')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUplaod',
            fields=[
                ('Image_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Image_Title', models.CharField(default='', max_length=1000)),
                ('Image_Name', models.ImageField(upload_to=lander_portal.models.user_directory_path)),
                ('Creater_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses_exams',
            name='Subj_Id',
            field=models.ManyToManyField(to='lander_portal.subjects_tostudy'),
        ),
        migrations.CreateModel(
            name='Article_data',
            fields=[
                ('Article_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Article_Heading', models.CharField(default=' ', max_length=4000)),
                ('Article_detail', ckeditor.fields.RichTextField()),
                ('Article_Add_Time', models.DateField(auto_now_add=True)),
                ('Article_Update_Time', models.DateField(auto_now=True)),
                ('Creater_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Tag_Id', models.ManyToManyField(to='lander_portal.tags_tomatch')),
            ],
        ),
    ]
