# Generated by Django 4.0.3 on 2022-03-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lander_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses_exams',
            old_name='Exam_fullform',
            new_name='Exam_shortForm',
        ),
    ]
