# Generated by Django 4.0.3 on 2022-03-27 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lander_portal', '0002_rename_exam_fullform_courses_exams_exam_shortform'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects_tostudy',
            name='Subj_Desc',
            field=ckeditor.fields.RichTextField(default='Add Subject Description'),
        ),
        migrations.AddField(
            model_name='topics_comes',
            name='Topic_Desc',
            field=ckeditor.fields.RichTextField(default='Add Topic Description'),
        ),
    ]
